FROM golang:1.25-alpine as builder
RUN  adduser -D -u  1000 appuser
WORKDIR /app
COPY go.mod go.sum ./
RUN  go mod download

COPY . . 

RUN  CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server


FROM scratch

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
USER appuser
COPY --from=builder /app/server /server
EXPOSE 8080
ENTRYPOINT [ "/server" ]
CMD [ "--port","8080" ]


